# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bloc < Formula
  desc "CLI to discover and run local AI models using community recipes"
  homepage "https://bloc-theta.vercel.app/"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.7.0/bloc_darwin_amd64.tar.gz"
      sha256 "e652939371a821d4a082c7b2af8be72b31e17e955e33416b4f3eafd60d921558"

      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.7.0/bloc_darwin_arm64.tar.gz"
      sha256 "6f6d8b7404d929139a925c79a0e0fe773a8d21f3cf34091983c935d821bda262"

      def install
        bin.install "bloc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.7.0/bloc_linux_amd64.tar.gz"
      sha256 "2b17ba4e5612bb6fc5943e75f9e479dce56dc4c57c77045e5bda3faf3942b9ea"
      def install
        bin.install "bloc"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/Bloc-ai/Bloc/releases/download/v0.7.0/bloc_linux_arm64.tar.gz"
      sha256 "dd9cca8584dd553631f59e46aa4b7ae66bd46e0e47e006a6ffc479a52880e7cc"
      def install
        bin.install "bloc"
      end
    end
  end
end
